# vetor produtos (mantido conforme original)
produtos = [
    ["Soja","Inseticida","Curbix","Bayer",0.75,"L/ha",320],
    ["Soja","Fungicida","Fox Xpro","Bayer",0.40,"L/ha",280],
    ["Soja","Fertilizante Foliar","Bayfolan","Bayer",2.0,"L/ha",50],
    ["Soja","Inseticida","Pirate","BASF",0.60,"L/ha",290],
    ["Soja","Fungicida","Orkestra","BASF",0.35,"L/ha",300],
    ["Soja","Fertilizante Foliar","Basfoliar Kelp","BASF",2.0,"L/ha",45],
    ["Soja","Inseticida","Engeo Pleno","Syngenta",0.25,"L/ha",340],
    ["Soja","Fungicida","Elatus","Syngenta",0.20,"L/ha",450],
    ["Soja","Fertilizante Foliar","Quantis","Syngenta",2.0,"L/ha",60],
    ["Milho","Inseticida","Belt","Bayer",0.10,"L/ha",950],
    ["Milho","Fungicida","Stratego Pro","Bayer",0.40,"L/ha",240],
    ["Milho","Fertilizante Foliar","Bayfolan","Bayer",2.0,"L/ha",50],
    ["Milho","Inseticida","Fastac","BASF",0.20,"L/ha",190],
    ["Milho","Fungicida","Orkestra","BASF",0.45,"L/ha",300],
    ["Milho","Fertilizante Foliar","Basfoliar 20-20-20","BASF",3.0,"kg/ha",32],
    ["Milho","Inseticida","Ampligo","Syngenta",0.20,"L/ha",380],
    ["Milho","Fungicida","Miravis Neo","Syngenta",0.30,"L/ha",420],
    ["Milho","Fertilizante Foliar","Quantis","Syngenta",2.0,"L/ha",60],
    ["Café","Inseticida","Sivanto Prime","Bayer",0.75,"L/ha",420],
    ["Café","Fungicida","Sphere Max","Bayer",0.60,"L/ha",270],
    ["Café","Fertilizante Foliar","Bayfolan","Bayer",2.0,"L/ha",50],
    ["Café","Inseticida","Fastac","BASF",0.30,"L/ha",190],
    ["Café","Fungicida","Opera","BASF",0.75,"L/ha",250],
    ["Café","Fertilizante Foliar","Basfoliar Zn","BASF",1.5,"L/ha",38],
    ["Café","Inseticida","Actara","Syngenta",0.20,"L/ha",410],
    ["Café","Fungicida","Amistar Top","Syngenta",0.50,"L/ha",300],
    ["Café","Fertilizante Foliar","Quantis","Syngenta",2.0,"L/ha",60],
    ["Trigo","Inseticida","Decis","Bayer",0.20,"L/ha",180],
    ["Trigo","Fungicida","Fox","Bayer",0.50,"L/ha",230],
    ["Trigo","Fertilizante Foliar","Bayfolan","Bayer",2.0,"L/ha",50],
    ["Trigo","Inseticida","Fastac","BASF",0.20,"L/ha",190],
    ["Trigo","Fungicida","Opera","BASF",0.60,"L/ha",250],
    ["Trigo","Fertilizante Foliar","Basfoliar Boro","BASF",1.0,"L/ha",35],
    ["Trigo","Inseticida","Karate Zeon","Syngenta",0.15,"L/ha",210],
    ["Trigo","Fungicida","Trivapro","Syngenta",0.40,"L/ha",320],
    ["Trigo","Fertilizante Foliar","Quantis","Syngenta",2.0,"L/ha",60],
    ["Cana-de-açúcar","Inseticida","Connect","Bayer",1.0,"L/ha",150],
    ["Cana-de-açúcar","Fungicida","Sphere Max","Bayer",0.70,"L/ha",270],
    ["Cana-de-açúcar","Fertilizante Foliar","Bayfolan","Bayer",2.0,"L/ha",50],
    ["Cana-de-açúcar","Inseticida","Fastac","BASF",0.30,"L/ha",190],
    ["Cana-de-açúcar","Fungicida","Opera","BASF",0.75,"L/ha",250],
    ["Cana-de-açúcar","Fertilizante Foliar","Basfoliar Ativ","BASF",2.0,"L/ha",40],
    ["Cana-de-açúcar","Inseticida","Engeo Pleno","Syngenta",0.30,"L/ha",340],
    ["Cana-de-açúcar","Fungicida","Amistar","Syngenta",0.60,"L/ha",290],
    ["Cana-de-açúcar","Fertilizante Foliar","Quantis","Syngenta",2.0,"L/ha",60]
]